options:
  noEmptyString: true
common:
  formXmlCompliant: true
basicAuth: true # get credentials from config and add basic auth
# This block refers to auto help generation
help:
  title: Electric Flow integration for TOPdesk
  description: Electric Flow integration for TOPdesk
  links:
    - https://developers.topdesk.com/
  hasConfig: true
procedures:
  - name: createOperatorChange
    stepName: createOperatorChange
    description: Create a new change for an operator.
    endpoint: '#{{instance}}/operatorChanges'
    method: POST
    hasConfig: true
    attachCredentials: true
    payload: |
    {"briefDescription" : "#{title}",
     "request" : "#{briefDescription}",
     "#{data}"
    }
    contentType: application/json
    outputParameters:
      change: JSON representation of the created operator change
      changeId: Change ID of the created operator change
    basicAuth: true
     # credentials will be turned into basic auth header
    canSkipAuth: true
     # if no credentials found, the procedure won't fail, the request will be made without credentials
    parameters:
      - property: title
        type: entry
        label: Incident title
        documentation: Change title (limited to 80 characters)
        required: 1
      - property: briefDescription
        type: textarea
        label: Brief Description fo the change
        required: 1
        documentation: Brief Description.
      - property: data
        type: textarea
        label: Change payload
        required: 1
        documentation: The JSON content of the operator change to create.
